font_family DejaVu Sans Mono
font_size 14.0

background #282828
foreground #c8c3b7

cursor #c8c3b7
cursor_text_color #282828
cursor_shape block
cursor_blink_interval 0

selection_background #504945
selection_foreground #d5d0c4

window_padding_width 5
background_opacity 1.0
confirm_os_window_close 0
enable_audio_bell no

tab_bar_min_tabs 2
tab_bar_style separator

color0 #282828
color1 #9c7a72
color2 #909178
color3 #ada084
color4 #90938c
color5 #9b8e88
color6 #8b9990
color7 #c8c3b7
color8 #665c54
color9 #b08c82
color10 #a3a48b
color11 #b8aa91
color12 #a4a79f
color13 #afa09a
color14 #9fafaa
color15 #d5d0c4

active_tab_foreground #c8c3b7
active_tab_background #504945
inactive_tab_foreground #aaa69b
inactive_tab_background #282828
active_tab_font_style normal

# Copy the most recent non-empty shell command output to the clipboard.
map ctrl+shift+y copy_last_command_output
