# Beacon aerospace workstation shell
default_border pixel 1
default_floating_border pixel 1

# class                  border   background text     indicator child_border
client.focused           #8297FF  #0B0D10   #F1F3F5  #8297FF  #8297FF
client.focused_inactive  #20242A  #070809   #A5AAB1  #20242A  #20242A
client.unfocused         #20242A  #050607   #676D76  #20242A  #20242A
client.urgent            #E46C78  #0B0D10   #F1F3F5  #E46C78  #E46C78
client.placeholder       #20242A  #050607   #676D76  #20242A  #20242A
client.background        #050607

exec_always --no-startup-id xsetroot -solid "#050607"
