font_family Terminus (TTF)
font_size 14.0

background #050306
foreground #cfc6d2

cursor #9a66b5
cursor_shape block
cursor_blink_interval 0

selection_background #2a1631
selection_foreground #eee8f0

window_padding_width 5
background_opacity 1.0
confirm_os_window_close 0
enable_audio_bell no

tab_bar_min_tabs 2
tab_bar_style separator

color0  #050306
color1  #8d4a63
color2  #687865
color3  #88765d
color4  #5c5278
color5  #6a3c7d
color6  #5d7075
color7  #cfc6d2

color8  #433a46
color9  #ad6079
color10 #84917e
color11 #a58c6c
color12 #776c9b
color13 #9a66b5
color14 #809297
color15 #eee8f0

modify_font cell_height 90%
modify_font cell_width 110%

# Copy the most recent non-empty shell command output to the clipboard.
map ctrl+shift+y copy_last_command_output
